model_parameters:
  model_name: "Qwen/Qwen3-4B"
  revision: "main"
  dtype: "float16"
  compile: false
  model_parallel: false
  batch_size: 1
  multichoice_continuations_start_space: null # If true/false, will force multiple choice continuations to start/not start with a space. If none, will do nothing
  generation_parameters:
    temperature: 0.2
    top_p: 0.9
