model_parameters:
  model_name: "Qwen/Qwen2.5-VL-7B-Instruct"
  revision: "cc594898137f460bfe9f0759e9844b3ce807cfb5"
  dtype: "float16"
  compile: false
  model_parallel: false
  batch_size: 1
  generation_parameters:
    temperature: 0.2
    top_p: 0.9
